// ═════════════════════════ Manchester (EGCC): Academy guided exercises ═════════════════════════
// The three exercises of the Ringway endorsement (schedules in egcc.js EXERCISES, keys rdep, rarr, rmix). The usual
// south-westerly puts the westerly configuration in use: land 23R (runway 1, by the terminals), depart 23L (runway 2,
// to the south-east), so every departure crosses runway 1 on its way out.
const egccCrossed = cs => { const a = A(cs); return (!!a && ((a.xok || []).includes('05L23R') || a.xing === '05L23R')) || st(cs,'HOLDPT','LINEUP','LINEDUP','TAKEOFF') || !!sn(cs).airborne; };
const egccCross = (cs, more) => ({ h: 'Cross runway 23R', p: `Runway 2 lies beyond runway 1, so the route stops at the runway-holding position before 23R and the crew calls. When nothing is landing or departing there, press <b>Cross runway 23R</b> or type <code>${cs} CROSS</code>.${more || ''}`,
  cmd: `${cs} CROSS`, ok: () => egccCrossed(cs), wait: () => { const a = A(cs); return !a || !a.hsAt; } });
const egccTaxiIn = (cs, more) => taxiInStep(cs, `Clear of the runway it stops and asks for taxi. Press <b>Taxi to stand</b> or type <code>${cs} TAXI</code>.${more || ''}`);
Object.assign(COACH, {
  rdep: [
    { h: 'Wait for the start-up call', p: 'RYR2232, a Ryanair 737 MAX on stand 43 at Terminal 3, is going to Málaga. In a moment the crew calls Manchester Ground for start-up and push back.', ok: () => !!(A('RYR2232') && A('RYR2232').need) || st('RYR2232','PUSH','READY','TAXI') },
    { h: 'Clearance, start-up and push', p: 'Select RYR2232 and press <b>Push</b>, or type <code>RYR2232 PUSH</code>. In the westerly configuration departures use runway 23L, so the clearance gives the KUXEM 1Y departure off 23L, climb altitude 5,000 feet (the UK transition altitude here, where every Manchester SID stops), the squawk and the QNH.', cmd: 'RYR2232 PUSH', ok: () => !!(A('RYR2232') && A('RYR2232').pushed) || st('RYR2232','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('RYR2232').airborne },
    { h: 'Taxi to the holding point', p: 'When the crew reports ready, press <b>Taxi…</b> to see the routings on the scope, or type <code>RYR2232 TAXI</code> for the recommended one. Runway 23L departures enter at its north-east end, Tango 1, or at the intermediate points Victor Alfa 1 and Victor Bravo 1.', cmd: 'RYR2232 TAXI', ok: () => st('RYR2232','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('RYR2232').airborne, wait: () => !st('RYR2232','READY') },
    egccCross('RYR2232', ' A crossing is always given on its own and read back in full.'),
    { h: 'Line up and wait', p: 'Manchester SIDs are agreed with Scottish Control in advance: no release is needed. When RYR2232 reports ready at the holding point, type <code>RYR2232 LU</code>.', cmd: 'RYR2232 LU', ok: () => st('RYR2232','LINEUP','LINEDUP','TAKEOFF') || sn('RYR2232').airborne, wait: () => !st('RYR2232','HOLDPT') },
    { h: 'Clear for take-off', p: 'Type <code>RYR2232 CTO</code>. The KUXEM 1Y climbs straight ahead, turns right at 3.2 miles onto the Manchester VOR 253 radial out over the Cheshire Plain, then heads south-west for KUXEM over North Wales.', cmd: 'RYR2232 CTO', ok: () => sn('RYR2232').takeoff || sn('RYR2232').airborne },
    { h: 'Transfer to Manchester Radar', p: 'Once airborne, send it to Manchester Radar with <code>RYR2232 HO</code>.', cmd: 'RYR2232 HO', ok: () => (A('RYR2232') && A('RYR2232').freq === 'RAD') || sn('RYR2232').exit },
    { h: 'Climb it and hand it on', p: 'It levels at 5,000 feet under the Manchester TMA. When it asks for more, climb it to flight level 150 with <code>RYR2232 A150</code>. When it is ready for transfer, send it on to Scottish Control: <code>RYR2232 HO</code>.', cmd: ['RYR2232 A150', 'RYR2232 HO'], ok: () => (A('RYR2232') && A('RYR2232').handed) || sn('RYR2232').exit, wait: () => { const a = A('RYR2232'); return !!a && !/^(Request climb|Ready for transfer)/.test(a.need || ''); } }
  ],
  rarr: [
    { h: 'Take the check-in', p: 'KLM1071, a KLM Cityhopper E190 from Amsterdam, checks in on the LIBSO 1M arrival over the Pennines towards the ROSUN hold, north-east of the airport. Select it and give a descent: <code>KLM1071 A70</code> for 7,000 feet, the bottom of the ROSUN stack.', cmd: 'KLM1071 A70', ok: () => sn('KLM1071').cmd || sn('KLM1071').landed },
    { h: 'Clear the ILS 23R', p: 'Type <code>KLM1071 APP</code>. From ROSUN it is vectored onto a downwind and base, the way Manchester Director does it, to TICZU on the localiser at 3,500 feet. Keep it at 3,500 or above out east: the high moors of the Peak District start fifteen miles out.', cmd: 'KLM1071 APP', ok: () => !!(A('KLM1071') && A('KLM1071').app) || sn('KLM1071').landed },
    { h: 'Transfer to the Tower', p: 'Once it is established, send it to Manchester Tower on 118.630 with <code>KLM1071 HO</code>.', cmd: 'KLM1071 HO', ok: () => (A('KLM1071') && A('KLM1071').freq === 'TWR') || sn('KLM1071').landed, wait: () => { const a = A('KLM1071'); return !!a && a.mode !== 'FINAL'; } },
    { h: 'Clear to land', p: 'Type <code>KLM1071 CTL</code>. Clear it before four miles, where the crew checks the weather against the minima.', cmd: 'KLM1071 CTL', ok: () => !!(A('KLM1071') && A('KLM1071').ctl) || sn('KLM1071').landed },
    { h: 'Watch it vacate', p: 'After touchdown it slows and turns off to the right, towards the terminals. To pick the exit yourself, press an exit button or type <code>KLM1071 VAC</code> and the exit while it is still on the runway. It stops once its tail is past the holding point.', ok: () => (st('KLM1071','VACATING','ONSTAND') && !A('KLM1071').onRwy) || sn('KLM1071').onstand },
    egccTaxiIn('KLM1071', ' KLM parks at Terminal 2.')
  ],
  rmix: [
    { h: 'Two runways, two jobs', p: 'Manchester lands on one runway and departs from the other. EZY1916, an easyJet A321neo from Tenerife South, comes in on the AXCIS 1M towards MIRSI, south-west of the airport. KLM1072 (Terminal 2, stand 207) is going to Amsterdam and EXS298 (Terminal 2, stand 25) to Alicante. Start with the arrival: <code>EZY1916 APP</code>.', cmd: 'EZY1916 APP', ok: () => !!(A('EZY1916') && A('EZY1916').app) || sn('EZY1916').landed },
    { h: 'Push both departures', p: 'When they call for start, push them: <code>KLM1072 PUSH</code> and <code>EXS298 PUSH</code>. Both leave from 23L: KLM1072 on the SONEX 1Y, which turns right to the north and then east over the Pennines, EXS298 on the SANBA 1Y, which turns right and then left to the south past TABLY.', cmd: ['KLM1072 PUSH', 'EXS298 PUSH'], ok: () => ['KLM1072', 'EXS298'].every(c => !!(A(c) && A(c).pushed) || st(c,'TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn(c).airborne), wait: () => !['KLM1072', 'EXS298'].some(c => A(c) && A(c).need) },
    { h: 'Taxi them out', p: 'When they report ready: <code>KLM1072 TAXI</code> and <code>EXS298 TAXI</code>. Both routes cross runway 1, so each stops at the runway-holding position before 23R.', cmd: ['KLM1072 TAXI', 'EXS298 TAXI'], ok: () => ['KLM1072', 'EXS298'].every(c => st(c,'TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn(c).airborne), wait: () => !['KLM1072', 'EXS298'].some(c => st(c,'READY')) },
    { h: 'Cross between the landings', p: 'Runway 23R is the landing runway. Cross each departure only when no arrival is inside about four miles: <code>KLM1072 CROSS</code>, <code>EXS298 CROSS</code>. If EZY1916 is close in, keep them holding until it has landed and passed the crossing point.', cmd: ['KLM1072 CROSS', 'EXS298 CROSS'], ok: () => ['KLM1072', 'EXS298'].every(egccCrossed), wait: () => !['KLM1072', 'EXS298'].some(c => { const a = A(c); return !!a && a.hsAt; }) },
    { h: 'Clear them for take-off', p: 'Runway 23L is the departure runway, so EZY1916 does not stop them. Clear the first one in the queue at Tango 1 when it reports ready (<code>KLM1072 CTO</code> or <code>EXS298 CTO</code>), then the second once the first is airborne: both SIDs turn right at 3.2 miles before they split.', cmd: ['KLM1072 CTO', 'EXS298 CTO'], ok: () => ['KLM1072', 'EXS298'].every(c => sn(c).takeoff || sn(c).airborne), wait: () => !['KLM1072', 'EXS298'].some(c => st(c,'HOLDPT','LINEDUP')) },
    { h: 'Hand off the departures', p: 'Send both to Manchester Radar: <code>KLM1072 HO</code>, <code>EXS298 HO</code>.', cmd: ['KLM1072 HO', 'EXS298 HO'], ok: () => ['KLM1072', 'EXS298'].every(c => (A(c) && A(c).freq === 'RAD') || sn(c).exit), wait: () => ['KLM1072', 'EXS298'].some(c => A(c) && A(c).ground) },
    { h: 'Climb them and hand them on', p: 'Both level at 5,000 feet. When each asks for more, climb it with <code>A150</code>, and when it is ready for transfer send it on to Scottish Control with <code>HO</code>: <code>KLM1072 A150 HO</code>, <code>EXS298 A150 HO</code>.', cmd: ['KLM1072 A150 HO', 'EXS298 A150 HO'], ok: () => ['KLM1072', 'EXS298'].every(c => (A(c) && A(c).handed) || sn(c).exit), wait: () => !['KLM1072', 'EXS298'].some(c => { const a = A(c); return !!a && /^(Request climb|Ready for transfer)/.test(a.need || ''); }) },
    { h: 'Land EZY1916', p: 'Once it is established on the ILS 23R, send it to the Tower and clear it to land: <code>EZY1916 HO CTL</code>.', cmd: 'EZY1916 HO CTL', ok: () => !!(A('EZY1916') && A('EZY1916').ctl) || sn('EZY1916').landed, wait: () => { const a = A('EZY1916'); return !!a && a.mode !== 'FINAL'; } },
    egccTaxiIn('EZY1916', ' easyJet parks at Terminal 2.')
  ]
});
