// ═════════════════════════ London Gatwick (EGKK): Academy guided exercises ═════════════════════════
// The three exercises of the Gatwick endorsement (schedules in egkk.js EXERCISES, keys gdep, garr, gmix). The usual
// south-westerly puts runway 26L in use for arrivals and departures alike: one runway, mixed mode.
Object.assign(COACH, {
  gdep: [
    { h: 'Wait for the start-up call', p: 'EZY8203, an easyJet A320neo on stand 553 at the North Terminal, is going to Málaga. In a moment the crew calls Gatwick Ground for start-up and push back.', ok: () => !!(A('EZY8203') && A('EZY8203').need) || st('EZY8203','PUSH','READY','TAXI') },
    { h: 'Clearance, start-up and push', p: 'Select EZY8203 and press <b>Push</b>, or type <code>EZY8203 PUSH</code>. The clearance gives the HARDY 1X departure, climb altitude 6,000 feet (where the SID stops), the squawk and the QNH. Every Gatwick SID is RNAV1 and has its own stop altitude: the Midhurst ones stop at 4,000.', cmd: 'EZY8203 PUSH', ok: () => !!(A('EZY8203') && A('EZY8203').pushed) || st('EZY8203','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('EZY8203').airborne },
    { h: 'Taxi to the holding point', p: 'Runway 26L departures enter at the east end: Alfa 1, Bravo 1, or Mike 1 on the starter extension. When the crew reports ready, press <b>Taxi…</b> and hover the routings to see them on the scope, or type <code>EZY8203 TAXI</code> for the recommended one. It stops at the runway-holding position, the yellow lines across the taxiway.', cmd: 'EZY8203 TAXI', ok: () => st('EZY8203','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('EZY8203').airborne },
    { h: 'Line up and wait', p: 'Gatwick SIDs are agreed with London Control in advance: no release is needed. When EZY8203 reports ready at the holding point, type <code>EZY8203 LU</code>. It lines up straight from the holding point: there are no turning pads.', cmd: 'EZY8203 LU', ok: () => st('EZY8203','LINEUP','LINEDUP','TAKEOFF') || sn('EZY8203').airborne, wait: () => !st('EZY8203','HOLDPT') },
    { h: 'Clear for take-off', p: 'Type <code>EZY8203 CTO</code>. The HARDY 1X climbs straight ahead to KKW06, past Horsham, then turns south for the coast at Bognor.', cmd: 'EZY8203 CTO', ok: () => sn('EZY8203').takeoff || sn('EZY8203').airborne },
    { h: 'Transfer to London Control', p: 'Once airborne, send it to London Control with <code>EZY8203 HO</code>. Gatwick Tower keeps departures only a minute or two.', cmd: 'EZY8203 HO', ok: () => (A('EZY8203') && A('EZY8203').freq === 'RAD') || sn('EZY8203').exit },
    { h: 'Climb it and hand it on', p: 'It levels at 6,000 feet under the London TMA. When it asks for more, climb it with <code>EZY8203 A150</code>, flight level 150 (the transition altitude is 6,000 ft). When it is ready for transfer, send it to the next London Control sector: <code>EZY8203 HO</code>.', cmd: ['EZY8203 A150', 'EZY8203 HO'], ok: () => (A('EZY8203') && A('EZY8203').handed) || sn('EZY8203').exit, wait: () => { const a = A('EZY8203'); return !!a && !/^(Request climb|Ready for transfer)/.test(a.need || ''); } }
  ],
  garr: [
    { h: 'Take the check-in', p: 'BAW2616, a BA Euroflyer A320 from Malta, checks in on the KUNAV 1G arrival towards the TIMBA hold, south-east of the airport. Select it and give a descent: <code>BAW2616 A50</code> for 5,000 feet.', cmd: 'BAW2616 A50', ok: () => sn('BAW2616').cmd || sn('BAW2616').landed },
    { h: 'Clear the ILS 26L', p: 'Type <code>BAW2616 APP</code>. From TIMBA it is vectored round a downwind and base, the way Gatwick Director does it, onto the localiser at OLEVI, 10.6 miles east of the airport at 3,000 feet. The glidepath is a normal 3°.', cmd: 'BAW2616 APP', ok: () => !!(A('BAW2616') && A('BAW2616').app) || sn('BAW2616').landed },
    { h: 'Transfer to the Tower', p: 'Once it is established, send it to Gatwick Tower on 124.230 with <code>BAW2616 HO</code>.', cmd: 'BAW2616 HO', ok: () => (A('BAW2616') && A('BAW2616').freq === 'TWR') || sn('BAW2616').landed, wait: () => { const a = A('BAW2616'); return !!a && a.mode !== 'FINAL'; } },
    { h: 'Clear to land', p: 'Type <code>BAW2616 CTL</code>. Clear it before four miles, where the crew checks the weather against the minima.', cmd: 'BAW2616 CTL', ok: () => !!(A('BAW2616') && A('BAW2616').ctl) || sn('BAW2616').landed },
    { h: 'Watch it vacate', p: 'After touchdown it slows and leaves by a rapid exit: Echo Romeo, or Foxtrot Romeo (hot spot HS1) if it rolls further. To pick the exit yourself, press an exit button or type <code>BAW2616 VAC FR</code> while it is still on the runway. It stops once its tail is past the holding point.', ok: () => (st('BAW2616','VACATING','ONSTAND') && !A('BAW2616').onRwy) || sn('BAW2616').onstand },
    taxiInStep('BAW2616', 'Clear of 26L it stops and asks for taxi. Assign a stand at its terminal (the North Terminal for British Airways) and taxi it in: press <b>Taxi to stand</b> or type <code>BAW2616 TAXI</code>. Old runway 08L/26R is now part of taxiway Juliett, so it may route along it.')
  ],
  gmix: [
    { h: 'One runway, both ways', p: 'Gatwick runs arrivals and departures on the same runway. TOM4249, a TUI 737 MAX from Rhodes, is on the KUNAV 1G towards TIMBA. EZY8492 (South Terminal, stand 31) is going to Geneva and BAW2662 (North Terminal, stand 555) to Faro. Start with the arrival: <code>TOM4249 A50 APP</code>.', cmd: 'TOM4249 A50 APP', ok: () => !!(A('TOM4249') && A('TOM4249').app) || sn('TOM4249').landed },
    { h: 'Push EZY8492', p: 'When EZY8492 calls for start, push it: <code>EZY8492 PUSH</code>. Its SID is the WIZAD 1X.', cmd: 'EZY8492 PUSH', ok: () => !!(A('EZY8492') && A('EZY8492').pushed) || st('EZY8492','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('EZY8492').airborne, wait: () => { const a = A('EZY8492'); return !a || !a.need; } },
    { h: 'Taxi EZY8492', p: 'When it reports ready: <code>EZY8492 TAXI</code>. From the South Terminal the 26L holding points are close by.', cmd: 'EZY8492 TAXI', ok: () => st('EZY8492','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('EZY8492').airborne, wait: () => { const a = A('EZY8492'); return !a || a.state !== 'READY'; } },
    { h: 'Get it away before the arrival', p: 'TOM4249 is still well out. With a gap like that, the departure goes first: <code>EZY8492 LU</code>, then <code>EZY8492 CTO</code>. At Gatwick a departure needs about two minutes of runway between two arrivals.', cmd: ['EZY8492 LU', 'EZY8492 CTO'], ok: () => sn('EZY8492').takeoff || sn('EZY8492').airborne, wait: () => !st('EZY8492','HOLDPT','LINEDUP') },
    { h: 'Hand off EZY8492', p: 'Send it to London Control: <code>EZY8492 HO</code>.', cmd: 'EZY8492 HO', ok: () => (A('EZY8492') && A('EZY8492').freq === 'RAD') || sn('EZY8492').exit, wait: () => { const a = A('EZY8492'); return !a || a.ground; } },
    { h: 'Push and taxi BAW2662', p: 'BAW2662 is ready at the North Terminal: <code>BAW2662 PUSH</code>, then <code>BAW2662 TAXI</code> when it reports ready.', get cmd(){ const a = A('BAW2662'); return a && a.state === 'READY' ? 'BAW2662 TAXI' : 'BAW2662 PUSH'; },
      ok: () => st('BAW2662','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('BAW2662').airborne, wait: () => { const a = A('BAW2662'); return !a || !a.need; } },
    { h: 'Land TOM4249', p: 'TOM4249 is on the localiser now. Send it to the Tower and clear it to land: <code>TOM4249 HO CTL</code>.', cmd: 'TOM4249 HO CTL', ok: () => !!(A('TOM4249') && A('TOM4249').ctl) || sn('TOM4249').landed, wait: () => { const a = A('TOM4249'); return !a || a.mode !== 'FINAL'; } },
    { h: 'Hold BAW2662 until the runway is clear', p: 'BAW2662 waits at its holding point while TOM4249 lands. Once the 737 is off the runway, line BAW2662 up and clear it: <code>BAW2662 LU</code>, <code>BAW2662 CTO</code>. Never clear a departure while the arrival is still on the runway.', cmd: ['BAW2662 LU', 'BAW2662 CTO'], ok: () => sn('BAW2662').takeoff || sn('BAW2662').airborne,
      wait: () => { const a = A('BAW2662'), t = A('TOM4249'); return !a || !st('BAW2662','HOLDPT','LINEDUP') || (!!t && !sn('TOM4249').landed) || S.acs.some(o => o !== a && onRunway(o, '26L')); } },
    taxiInStep('TOM4249', 'TOM4249 waits clear of the runway. Taxi it to the North Terminal: <code>TOM4249 TAXI</code>.'),
    { h: 'Hand off BAW2662', p: 'Send BAW2662 to London Control: <code>BAW2662 HO</code>.', cmd: 'BAW2662 HO', ok: () => (A('BAW2662') && A('BAW2662').freq === 'RAD') || sn('BAW2662').exit, wait: () => { const a = A('BAW2662'); return !a || a.ground; } }
  ]
});
