// ═════════════════════════ London City (EGLC): Academy guided exercises ═════════════════════════
// The three exercises of the London City endorsement (schedules in eglc.js EXERCISES, keys cdep, carr, ceast).
Object.assign(COACH, {
  cdep: [
    { h: 'Wait for the start-up call', p: 'CFE8703, a BA CityFlyer Embraer 190 on stand 5, is going to Edinburgh. In a moment the crew asks for start-up and push back.', ok: () => !!(A('CFE8703') && A('CFE8703').need) || st('CFE8703','PUSH','READY','TAXI') },
    { h: 'Approve start-up and push', p: 'Select CFE8703 and press <b>Push</b>, or type <code>CFE8703 PUSH</code>. The clearance gives the BPK 1A departure, climb to 3,000 feet (every London City SID stops there) and a squawk. The tug pushes it back onto taxiway Tango facing east.', cmd: 'CFE8703 PUSH', ok: () => !!(A('CFE8703') && A('CFE8703').pushed) || st('CFE8703','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('CFE8703').airborne },
    { h: 'Taxi to holding point Mike', p: 'Runway 27 departures use the full length from Mike, at the far east end. When the crew reports ready, type <code>CFE8703 TAXI M</code>. It taxies east along Tango, past the east apron.', cmd: 'CFE8703 TAXI M', ok: () => st('CFE8703','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('CFE8703').airborne },
    { h: 'Request the release', p: 'London City sits under the London TMA, and every departure needs a release from Thames Radar and London Control before take-off. Press <b>Request release</b> or type <code>CFE8703 REL</code>. The call back comes on the landline (pink in the log).', cmd: 'CFE8703 REL', ok: () => !!(A('CFE8703') && A('CFE8703').rel) || sn('CFE8703').airborne },
    { h: 'Line up', p: 'Mike joins the runway at the 27 end, so there is no backtrack. Type <code>CFE8703 LU</code>.', cmd: 'CFE8703 LU', ok: () => st('CFE8703','LINEUP','LINEDUP','TAKEOFF') || sn('CFE8703').airborne },
    { h: 'Clear for take-off', p: 'With the release in, type <code>CFE8703 CTO</code>. The SID climbs straight ahead and may not turn below 1,102 feet, then follows its RNAV track north to BPK.', cmd: 'CFE8703 CTO', ok: () => sn('CFE8703').takeoff || sn('CFE8703').airborne, wait: () => { const a = A('CFE8703'); return !!a && !(a.rel && a.rel.st === 'OK'); } },
    { h: 'Transfer to Thames', p: 'Once airborne, send it to Thames Director on 132.700 with <code>CFE8703 HO</code>.', cmd: 'CFE8703 HO', ok: () => (A('CFE8703') && A('CFE8703').freq === 'RAD') || sn('CFE8703').exit },
    { h: 'Climb it and hand it to London Control', p: 'It levels at 3,000 feet under the Heathrow and Stansted traffic. When it asks for more, climb it with <code>CFE8703 A80</code>. When it is ready for transfer, send it to London Control: <code>CFE8703 HO</code>.', cmd: ['CFE8703 A80', 'CFE8703 HO'], ok: () => (A('CFE8703') && A('CFE8703').handed) || sn('CFE8703').exit, wait: () => { const a = A('CFE8703'); return !!a && a.need !== 'Ready for transfer'; } }
  ],
  carr: [
    { h: 'Take the initial call', p: 'KLC983 from Amsterdam, a KLM Cityhopper Embraer 195-E2, calls on the SUMUM 1C towards the JACKO hold. Select it and give a descent: <code>KLC983 A50</code> for 5,000 feet.', cmd: 'KLC983 A50', ok: () => sn('KLC983').cmd || sn('KLC983').landed },
    { h: 'Clear the ILS', p: 'Type <code>KLC983 APP</code>. It flies the LAVNO transition onto the runway 27 localiser at 3,000 feet and starts down the 5.5° glidepath about 5 miles out: almost twice as steep as a normal ILS, so only steep-approach approved types come to City.', cmd: 'KLC983 APP', ok: () => !!(A('KLC983') && A('KLC983').app) || sn('KLC983').landed },
    { h: 'Transfer to the Tower', p: 'Once it is established, send it to City Tower on 118.080 with <code>KLC983 HO</code>. The tower is a remote digital tower: the controllers sit at Swanwick and watch the runway through cameras on a mast by the King George V Dock.', cmd: 'KLC983 HO', ok: () => (A('KLC983') && A('KLC983').freq === 'TWR') || sn('KLC983').landed },
    { h: 'Clear to land', p: 'Type <code>KLC983 CTL</code>. Clear it before four miles: that is where the crew checks the weather against the approach ban.', cmd: 'KLC983 CTL', ok: () => !!(A('KLC983') && A('KLC983').ctl) || sn('KLC983').landed },
    { h: 'Watch the landing', p: 'The steep approach puts it down close to the threshold. After touchdown it rolls out and picks its own exit.', ok: () => sn('KLC983').landed && st('KLC983','ROLLED','VACATING','ONSTAND') },
    { h: 'Watch it vacate', p: 'It vacates by itself at the first exit ahead (Echo, Delta or Charlie) and taxies along Tango to its stand. To pick the exit yourself, press its button or type <code>KLC983 VAC D</code> while it is still on the runway.', ok: () => (st('KLC983','VACATING','ONSTAND') && !A('KLC983').onRwy) || sn('KLC983').onstand }
  ],
  ceast: [
    { h: 'Runway 09 today', p: 'An easterly is blowing, so runway 09 is in use and everything runs the other way. CFE8723 on stand 6 is going to Dublin, and SWR458 from Geneva is inbound round the south of London. Get the departure away first. Wait for its start-up call.', ok: () => !!(A('CFE8723') && A('CFE8723').need) || st('CFE8723','PUSH','READY','TAXI') },
    { h: 'Push facing west', p: 'Runway 09 departures leave from Alpha at the west end, so push it facing west: <code>CFE8723 PUSH W</code>. Its SID is the SAXBI 1H.', cmd: 'CFE8723 PUSH W', ok: () => !!(A('CFE8723') && A('CFE8723').pushed) || st('CFE8723','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('CFE8723').airborne },
    { h: 'Taxi to Alpha', p: 'When it reports ready: <code>CFE8723 TAXI A</code>. Alpha is hot spot HS1, where the GA apron taxilane, stand 10 and the holding point sit close together.', cmd: 'CFE8723 TAXI A', ok: () => st('CFE8723','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('CFE8723').airborne },
    { h: 'Request the release', p: 'Type <code>CFE8723 REL</code> and wait for London to call back.', cmd: 'CFE8723 REL', ok: () => !!(A('CFE8723') && A('CFE8723').rel) || sn('CFE8723').airborne },
    { h: 'Line up', p: 'Alpha joins the runway at the 09 end: <code>CFE8723 LU</code>.', cmd: 'CFE8723 LU', ok: () => st('CFE8723','LINEUP','LINEDUP','TAKEOFF') || sn('CFE8723').airborne },
    { h: 'Clear for take-off', p: 'With the release in: <code>CFE8723 CTO</code>. It climbs straight ahead over the docks and may not turn below 570 feet.', cmd: 'CFE8723 CTO', ok: () => sn('CFE8723').takeoff || sn('CFE8723').airborne, wait: () => { const a = A('CFE8723'); return !!a && !(a.rel && a.rel.st === 'OK'); } },
    { h: 'Hand it to Thames', p: 'Once airborne: <code>CFE8723 HO</code>.', cmd: 'CFE8723 HO', ok: () => (A('CFE8723') && A('CFE8723').freq === 'RAD') || sn('CFE8723').exit },
    { h: 'Clear the ILS 09', p: 'Now SWR458. Its ODLEG 1G transition runs west along the river, south of the city and back north onto a short final past Canary Wharf, whose towers rise to 771 feet. Clear it: <code>SWR458 APP</code>. The localiser starts only 4.9 miles out, at 2,000 feet, and the glidepath is 5.5°.', cmd: 'SWR458 APP', ok: () => !!(A('SWR458') && A('SWR458').app) || sn('SWR458').landed },
    { h: 'Transfer to the Tower', p: 'Once it is established on the localiser, send it to City Tower: <code>SWR458 HO</code>. To save time you can send it direct to ODLEG with <code>SWR458 DCT ODLEG</code> first.', cmd: 'SWR458 HO', ok: () => (A('SWR458') && A('SWR458').freq === 'TWR') || sn('SWR458').landed, wait: () => { const a = A('SWR458'); return !!a && a.mode !== 'FINAL'; } },
    { h: 'Clear to land', p: 'Type <code>SWR458 CTL</code> before the four-mile check.', cmd: 'SWR458 CTL', ok: () => !!(A('SWR458') && A('SWR458').ctl) || sn('SWR458').landed },
    { h: 'Vacate', p: 'It vacates by itself as it slows: rolling east, it turns off ahead at Foxtrot or Kilo and taxies back along Tango. <code>SWR458 VAC</code> and an exit overrides its choice.', ok: () => st('SWR458','VACATING','ONSTAND') || sn('SWR458').onstand, wait: () => { const a = A('SWR458'); return !!a && !['ROLLED','ROLLOUT'].includes(a.state); } }
  ]
});
