// ═════════════════════════ New York JFK (KJFK): Academy guided exercises ═════════════════════════
// The three exercises of the Kennedy endorsement (schedules in kjfk.js EXERCISES, keys kdep, karr, kcross). In the
// south-west flow arrivals land 22L and departures leave from 22R; Kennedy uses FAA phraseology.
Object.assign(COACH, {
  kdep: [
    { h: 'Wait for the call', p: 'DAL1103, a Delta A321 at gate B31 on Terminal 4, is going to Atlanta. A south-westerly sea breeze means arrivals land 22L and departures leave from 22R. In a moment the crew calls Ground, ready to push.', ok: () => !!(A('DAL1103') && A('DAL1103').need) || st('DAL1103','PUSH','READY','TAXI') },
    { h: 'Clearance and push back', p: 'Select DAL1103 and press <b>Push</b>, or type <code>DAL1103 PUSH</code>. In one call it gets its IFR clearance (the Kennedy Five, radar vectors, maintain 5,000 ft, departure frequency and squawk) and the approval to push. Note the altimeter: in the US it is in inches of mercury, here 29.97.', cmd: 'DAL1103 PUSH', ok: () => !!(A('DAL1103') && A('DAL1103').pushed) || st('DAL1103','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('DAL1103').airborne },
    { h: 'Taxi to runway 22R', p: 'Runway 22R departures enter at its north-east end, from taxiway Foxtrot Bravo. When the crew reports ready, press <b>Taxi…</b> and pick a routing, or type <code>DAL1103 TAXI</code> for the recommended one. FAA style, the clearance names the runway first, then every taxiway in order.', cmd: 'DAL1103 TAXI', ok: () => st('DAL1103','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('DAL1103').airborne },
    { h: 'Line up and wait', p: 'No release is needed for Atlanta: New York only asks for one on flow-restricted routes. When DAL1103 is holding short, type <code>DAL1103 LU</code>. "Line up and wait" is the FAA wording for lining up.', cmd: 'DAL1103 LU', ok: () => st('DAL1103','LINEUP','LINEDUP','TAKEOFF') || sn('DAL1103').airborne, wait: () => !st('DAL1103','HOLDPT') },
    { h: 'Clear for take-off', p: 'Type <code>DAL1103 CTO</code>. The Kennedy Five gives a heading by runway: off 22R it is heading 224. Note the order: wind first, then the runway, then "cleared for takeoff".', cmd: 'DAL1103 CTO', ok: () => sn('DAL1103').takeoff || sn('DAL1103').airborne },
    { h: 'Contact New York Departure', p: `Once airborne, send it to New York Departure on 135.9 with <code>DAL1103 HO</code>. It checks in climbing to 5,000 ft.`, cmd: 'DAL1103 HO', ok: () => (A('DAL1103') && A('DAL1103').freq === 'RAD') || sn('DAL1103').exit },
    { h: 'Climb and hand off to the Center', p: `When it asks for more, climb it: <code>DAL1103 A190</code> is "climb and maintain flight level one niner zero". Flight levels start at 18,000 ft in the US. When it is ready for transfer, send it to New York Center on ${NEXT_UNIT.SW[1]} with <code>DAL1103 HO</code>.`, cmd: ['DAL1103 A190', 'DAL1103 HO'], ok: () => (A('DAL1103') && A('DAL1103').handed) || sn('DAL1103').exit, wait: () => { const a = A('DAL1103'); return !!a && !/^(Request climb|Ready for transfer)/.test(a.need || ''); } }
  ],
  karr: [
    { h: 'Take the check-in', p: 'JBU702 from Boston checks in on the PARCH Four arrival, coming in from the east along Long Island. Select it and give a descent: <code>JBU702 A60</code>, "descend and maintain 6,000".', cmd: 'JBU702 A60', ok: () => sn('JBU702').cmd || sn('JBU702').landed },
    { h: 'Clear the ILS 22L', p: 'Type <code>JBU702 APP</code>. From ROBER and CRAIL it is vectored onto a base leg and joins the localizer at ROSLY at 3,000 ft. The clearance is "maintain 3,000 until established on the localizer, cleared ILS runway 22L approach".', cmd: 'JBU702 APP', ok: () => !!(A('JBU702') && A('JBU702').app) || sn('JBU702').landed },
    { h: 'Contact the Tower', p: 'Once it is established, send it to Kennedy Tower on 119.1, the frequency for 4R/22L, with <code>JBU702 HO</code>. The parallel 4L/22R has its own Tower frequency, 123.9.', cmd: 'JBU702 HO', ok: () => (A('JBU702') && A('JBU702').freq === 'TWR') || sn('JBU702').landed },
    { h: 'Clear to land', p: 'Type <code>JBU702 CTL</code>. ILS minimums are 200 ft and half a mile.', cmd: 'JBU702 CTL', ok: () => !!(A('JBU702') && A('JBU702').ctl) || sn('JBU702').landed },
    { h: 'Watch it vacate', p: 'After touchdown it slows and turns off by itself at a high-speed exit on the terminal side. To pick the exit yourself, press an exit button or type <code>JBU702 VAC J</code> while it is still on the runway.', ok: () => (st('JBU702','VACATING','ONSTAND') && !A('JBU702').onRwy) || sn('JBU702').onstand || !!(A('JBU702') && A('JBU702').hsAt) },
    taxiInStep('JBU702', 'Clear of 22L it stops and calls Ground for its gate. Press <b>Taxi to gate</b> or type <code>JBU702 TAXI</code>: "taxi to gate …, via …, hold short runway 22R". To send it to another gate, add the gate (<code>JBU702 TAXI 5-14</code>).', 'Taxi it to the gate'),
    { h: 'Cross runway 22R', p: 'Terminal 5 is on the far side of 22R, the departure runway. Every taxi route to it crosses, so the aircraft stops at the hold-short line and calls. Press <b>Cross runway 22R</b> or type <code>JBU702 CROSS</code>. A crossing is always given on its own and read back in full.', cmd: 'JBU702 CROSS', ok: () => { const a = A('JBU702'); return (!!a && (a.xok || []).includes('4L22R')) || !!(a && a.xing === '4L22R') || sn('JBU702').onstand || (!!a && a.kind === 'DEP'); }, wait: () => { const a = A('JBU702'); return !a || !a.hsAt; } },
    { h: 'Watch it taxi in', p: 'Once across it taxies to its gate on Terminal 5 and turns round for its next flight.', ok: () => sn('JBU702').onstand || (!!A('JBU702') && A('JBU702').kind === 'DEP') }
  ],
  kcross: [
    { h: 'Two flows, one crossing point', p: 'Arrivals land 22L, departures leave from 22R. AAL1 from Los Angeles is on the PUCKY One arrival and will need to cross 22R to reach Terminal 8. JBU101 at gate 5-12 is going to Boston, a route under flow control. Start with the arrival: <code>AAL1 A60 APP</code>.', cmd: 'AAL1 A60 APP', ok: () => !!(A('AAL1') && A('AAL1').app) || sn('AAL1').landed },
    { h: 'Push and taxi JBU101', p: 'When JBU101 calls, push it with <code>JBU101 PUSH</code>, then taxi it to 22R with <code>JBU101 TAXI</code>.', cmd: ['JBU101 PUSH', 'JBU101 TAXI'], ok: () => st('JBU101','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('JBU101').airborne, wait: () => { const a = A('JBU101'); return !a || !(a.need || a.pushed); } },
    { h: 'Call for release', p: 'Boston is under an Approval Request: the flight cannot go until New York Center releases it. Press <b>Request release</b> or type <code>JBU101 REL</code>. The Center calls back on the landline (pink in the log), sometimes with a "not before" time. Most Kennedy departures need no release.', cmd: 'JBU101 REL', ok: () => !!(A('JBU101') && A('JBU101').rel) || sn('JBU101').airborne },
    { h: 'Land AAL1', p: 'Send AAL1 to the Tower and clear it to land: <code>AAL1 HO CTL</code>.', cmd: 'AAL1 HO CTL', ok: () => !!(A('AAL1') && A('AAL1').ctl) || sn('AAL1').landed, wait: () => { const a = A('AAL1'); return !a || a.state !== 'FINAL'; } },
    taxiInStep('AAL1', 'AAL1 lands, vacates 22L and stops clear of it. Taxi it towards Terminal 8 with <code>AAL1 TAXI</code>: it stops again short of 22R.', 'Taxi AAL1 towards its gate'),
    { h: 'Depart JBU101 first', p: 'AAL1 will stop short of 22R. Keep it there while JBU101 goes: once the release is in, <code>JBU101 LU</code>, then <code>JBU101 CTO</code>. Never line up a departure on a runway someone is crossing. A release is only valid for about ten minutes: if it has run out, ask again with <code>JBU101 REL</code>.',
      get cmd(){ const a = A('JBU101'); return a && !(a.rel && ['OK','REQ'].includes(a.rel.st)) ? 'JBU101 REL' : ['JBU101 LU', 'JBU101 CTO']; },
      ok: () => sn('JBU101').takeoff || sn('JBU101').airborne,
      wait: () => { const a = A('JBU101'); if (!a || a.state !== 'HOLDPT') return true; if (!(a.rel && ['OK','REQ'].includes(a.rel.st))) return false; return !(a.rel.st === 'OK' && !(a.rel.nb && S.t < a.rel.nb)) || S.acs.some(o => o !== a && onRunway(o, '22R')); } },
    { h: 'Cross AAL1 behind it', p: 'When JBU101 is rolling and AAL1 is holding short, cross it: <code>AAL1 CROSS</code>. Its taxi to Terminal 8 continues on the other side.', cmd: 'AAL1 CROSS', ok: () => { const a = A('AAL1'); return (!!a && ((a.xok || []).includes('4L22R') || a.xing === '4L22R')) || sn('AAL1').onstand || (!!a && a.kind === 'DEP'); },
      wait: () => { const a = A('AAL1'), d = A('JBU101'); return !a || !a.hsAt || (!!d && d.ground); } },
    { h: 'Hand off JBU101', p: 'Send JBU101 to New York Departure with <code>JBU101 HO</code>, and later to the Center when it is ready.', cmd: 'JBU101 HO', ok: () => (A('JBU101') && A('JBU101').freq === 'RAD') || sn('JBU101').exit, wait: () => { const a = A('JBU101'); return !a || a.ground; } },
    { h: 'One more departure', p: 'DAL401 at B24 is going to Los Angeles: no release needed. Push, taxi and depart it: <code>DAL401 PUSH</code>, <code>DAL401 TAXI</code>, then <code>DAL401 CTO</code> at the runway.',
      get cmd(){ const a = A('DAL401'); return !a ? null : a.state === 'PARKED' ? 'DAL401 PUSH' : a.state === 'READY' ? 'DAL401 TAXI' : a.state === 'HOLDPT' ? 'DAL401 CTO' : null; },
      ok: () => sn('DAL401').takeoff || sn('DAL401').airborne,
      wait: () => { const a = A('DAL401'); return !a || !a.need || S.acs.some(o => o !== a && onRunway(o, '22R')); } }
  ]
});
