// ═════════════════════════ Madrid-Barajas (LEMD): Academy guided exercises ═════════════════════════
// The three exercises of the Barajas endorsement (schedules in lemd.js EXERCISES, keys ldep, larr, lmix). The usual
// light westerly puts the north flow in use: land 32L and 32R, depart 36L and 36R.
const lemdTaxiIn = (cs, more) => taxiInStep(cs, `Clear of the runway it stops and asks for taxi. Press <b>Taxi to stand</b> or type <code>${cs} TAXI</code>. If its route crosses runway 18R/36L it stops at the holding position on Zulu 7 or the ZW taxiways: clear it across with <code>${cs} CROSS</code> when nothing is landing or departing there.${more || ''}`);
Object.assign(COACH, {
  ldep: [
    { h: 'Wait for the start-up call', p: 'IBE3402, an Iberia A321 on stand 332 at Terminal 4, is going to Barcelona. In a moment the crew calls Barajas Ground for start-up and push back.', ok: () => !!(A('IBE3402') && A('IBE3402').need) || st('IBE3402','PUSH','READY','TAXI') },
    { h: 'Clearance, start-up and push', p: 'Select IBE3402 and press <b>Push</b>, or type <code>IBE3402 PUSH</code>. Terminal 4 departures use runway 36L in the north flow, so the clearance gives the PINAR 4N departure off 36L, climb altitude 13,000 feet (the Spanish transition altitude, where every Madrid SID stops), the squawk and the QNH.', cmd: 'IBE3402 PUSH', ok: () => !!(A('IBE3402') && A('IBE3402').pushed) || st('IBE3402','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('IBE3402').airborne },
    { h: 'Taxi to the holding point', p: 'Runway 36L departures enter at its south end: Zulu 1 to Zulu 4. When the crew reports ready, press <b>Taxi…</b> to see the routings on the scope (the 36R holding points are listed too), or type <code>IBE3402 TAXI</code> for the recommended one. It stops at the runway-holding position.', cmd: 'IBE3402 TAXI', ok: () => st('IBE3402','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('IBE3402').airborne },
    { h: 'Line up and wait', p: 'Madrid SIDs are agreed with Madrid Control in advance: no release is needed. When IBE3402 reports ready, type <code>IBE3402 LU</code>. It lines up straight from the holding point.', cmd: 'IBE3402 LU', ok: () => st('IBE3402','LINEUP','LINEDUP','TAKEOFF') || sn('IBE3402').airborne, wait: () => !st('IBE3402','HOLDPT') },
    { h: 'Clear for take-off', p: 'Type <code>IBE3402 CTO</code>. The PINAR 4N climbs north over San Sebastián de los Reyes (SSY), then turns east past Robledillo for PINAR. Departures off 36R at the same time are no problem: the two runways are 1,500 m apart and their SIDs diverge.', cmd: 'IBE3402 CTO', ok: () => sn('IBE3402').takeoff || sn('IBE3402').airborne },
    { h: 'Transfer to Madrid Departure', p: 'Once airborne, send it to Madrid Departure with <code>IBE3402 HO</code>.', cmd: 'IBE3402 HO', ok: () => (A('IBE3402') && A('IBE3402').freq === 'RAD') || sn('IBE3402').exit },
    { h: 'Climb it and hand it on', p: 'It levels at 13,000 feet. When it asks for more, climb it to flight level 200 with <code>IBE3402 A200</code>. When it is ready for transfer, send it on to Madrid Control: <code>IBE3402 HO</code>.', cmd: ['IBE3402 A200', 'IBE3402 HO'], ok: () => (A('IBE3402') && A('IBE3402').handed) || sn('IBE3402').exit, wait: () => { const a = A('IBE3402'); return !!a && !/^(Request climb|Ready for transfer)/.test(a.need || ''); } }
  ],
  larr: [
    { h: 'Two arrivals, two runways', p: 'IBE3162, an Iberia A321 from London Heathrow, checks in on the NONTU 5C arrival from the north. AEA1012, an Air Europa 737 from Palma, follows on the VILLA 4D from the east. In the north flow arrivals from the west side land on 32L and arrivals from the east side on 32R. Clear IBE3162 for the ILS: <code>IBE3162 APP</code>.', cmd: 'IBE3162 APP', ok: () => !!(A('IBE3162') && A('IBE3162').app) || sn('IBE3162').landed },
    { h: 'Clear the second ILS', p: 'Now clear AEA1012: <code>AEA1012 APP</code>. It comes off RUDBI by the published initial segment to MD12R and the ILS 32R, while IBE3162 flies FAFEQ, MD418 and MD414 to the ILS 32L. The approaches are independent: once both are on their localisers they may fly side by side.', cmd: 'AEA1012 APP', ok: () => !!(A('AEA1012') && A('AEA1012').app) || sn('AEA1012').landed },
    { h: 'Transfer and land AEA1012', p: 'AEA1012 has the shorter way in and reaches its localiser first. Once it is established, send it to Barajas Tower and clear it to land on 32R: <code>AEA1012 HO CTL</code>. Clear each arrival before four miles, where the crew checks the weather against the minima.', cmd: 'AEA1012 HO CTL', ok: () => !!(A('AEA1012') && A('AEA1012').ctl) || sn('AEA1012').landed, wait: () => { const a = A('AEA1012'); return !!a && a.mode !== 'FINAL'; } },
    lemdTaxiIn('AEA1012', ' Air Europa parks at Terminals 1-2-3.'),
    { h: 'Transfer and land IBE3162', p: 'IBE3162 comes round from the north by FAFEQ onto the ILS 32L. Once it is established: <code>IBE3162 HO CTL</code>.', cmd: 'IBE3162 HO CTL', ok: () => !!(A('IBE3162') && A('IBE3162').ctl) || sn('IBE3162').landed, wait: () => { const a = A('IBE3162'); return !!a && a.mode !== 'FINAL'; } },
    lemdTaxiIn('IBE3162', ' Iberia parks at Terminal 4.')
  ],
  lmix: [
    { h: 'Four runways at once', p: 'Two arrivals and two departures, one for each runway of the north flow. IBS3832 (Tenerife North) is on the SOTUK 5C for 32L and VLG1002 (Barcelona) on the ADUXO 3D for 32R. IBE3612 at Terminal 4S leaves from 36R for Bilbao; RYR5412 at Terminal 1 leaves from 36L for London Stansted. Start with the arrivals: <code>IBS3832 APP</code> and <code>VLG1002 APP</code>.', cmd: ['IBS3832 APP', 'VLG1002 APP'], ok: () => (!!(A('IBS3832') && A('IBS3832').app) || sn('IBS3832').landed) && (!!(A('VLG1002') && A('VLG1002').app) || sn('VLG1002').landed) },
    { h: 'Push both departures', p: 'When they call for start, push them: <code>IBE3612 PUSH</code> and <code>RYR5412 PUSH</code>. Each clearance names its own runway: 36R for Terminal 4S, 36L for Terminal 1.', cmd: ['IBE3612 PUSH', 'RYR5412 PUSH'], ok: () => ['IBE3612', 'RYR5412'].every(c => !!(A(c) && A(c).pushed) || st(c,'TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn(c).airborne), wait: () => !['IBE3612', 'RYR5412'].some(c => A(c) && A(c).need) },
    { h: 'Taxi each to its runway', p: 'When they report ready: <code>IBE3612 TAXI</code> takes it to the Yankee holding points of 36R, <code>RYR5412 TAXI</code> to the Zulu holding points of 36L.', cmd: ['IBE3612 TAXI', 'RYR5412 TAXI'], ok: () => ['IBE3612', 'RYR5412'].every(c => st(c,'TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn(c).airborne), wait: () => !['IBE3612', 'RYR5412'].some(c => st(c,'READY')) },
    { h: 'Clear both for take-off', p: 'The departure runways are not the landing runways, so the arrivals don\'t stop them. When each reports ready: <code>IBE3612 CTO</code> and <code>RYR5412 CTO</code>. Simultaneous departures off 36L and 36R are allowed: their SIDs diverge.', cmd: ['IBE3612 CTO', 'RYR5412 CTO'], ok: () => ['IBE3612', 'RYR5412'].every(c => sn(c).takeoff || sn(c).airborne), wait: () => !['IBE3612', 'RYR5412'].some(c => st(c,'HOLDPT','LINEDUP')) },
    { h: 'Hand off the departures', p: 'Send both to Madrid Departure: <code>IBE3612 HO</code>, <code>RYR5412 HO</code>.', cmd: ['IBE3612 HO', 'RYR5412 HO'], ok: () => ['IBE3612', 'RYR5412'].every(c => (A(c) && A(c).freq === 'RAD') || sn(c).exit), wait: () => ['IBE3612', 'RYR5412'].some(c => A(c) && A(c).ground) },
    { h: 'Climb them and hand them on', p: 'Both level at 13,000 feet. When each asks for more, climb it with <code>A200</code>, and when it is ready for transfer send it on to Madrid Control with <code>HO</code>: <code>IBE3612 A200 HO</code>, <code>RYR5412 A200 HO</code>.', cmd: ['IBE3612 A200 HO', 'RYR5412 A200 HO'], ok: () => ['IBE3612', 'RYR5412'].every(c => (A(c) && A(c).handed) || sn(c).exit), wait: () => !['IBE3612', 'RYR5412'].some(c => { const a = A(c); return !!a && /^(Request climb|Ready for transfer)/.test(a.need || ''); }) },
    { h: 'Land both arrivals', p: 'Once each is established, send it to the Tower and clear it to land: <code>IBS3832 HO CTL</code> on 32L and <code>VLG1002 HO CTL</code> on 32R.', cmd: ['IBS3832 HO CTL', 'VLG1002 HO CTL'], ok: () => ['IBS3832', 'VLG1002'].every(c => !!(A(c) && A(c).ctl) || sn(c).landed), wait: () => ['IBS3832', 'VLG1002'].every(c => { const a = A(c); return !!a && a.mode !== 'FINAL'; }) },
    lemdTaxiIn('IBS3832', ' Iberia Express parks at Terminal 4.'),
    lemdTaxiIn('VLG1002', ' Vueling parks at Terminal 4.')
  ]
});
