// ═════════════════════════ Innsbruck (LOWI): Academy guided exercises ═════════════════════════
// The three exercises of the Innsbruck endorsement (schedules in lowi.js EXERCISES, keys idep, iarr, ifoehn).
Object.assign(COACH, {
  idep: [
    { h: 'Wait for the start-up call', p: 'AUA904, an Austrian Embraer 195 on the south apron, is going to Vienna. A light westerly means arrivals land on 26 and departures leave on 08, towards them. In a moment the crew asks for start-up and push back.', ok: () => !!(A('AUA904') && A('AUA904').need) || st('AUA904','PUSH','READY','TAXI') },
    { h: 'Approve start-up and push', p: 'Select AUA904 and press <b>Push</b>, or type <code>AUA904 PUSH</code>. The clearance gives the OBEDI 3J departure, climb to 10,000 feet and a squawk, and the tug pushes it back facing west.', cmd: 'AUA904 PUSH', ok: () => !!(A('AUA904') && A('AUA904').pushed) || st('AUA904','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('AUA904').airborne },
    { h: 'Taxi to holding point Alpha', p: 'Runway 08 departures leave from Alpha, near the west end. When the crew reports ready, type <code>AUA904 TAXI A</code>.', cmd: 'AUA904 TAXI A', ok: () => st('AUA904','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('AUA904').airborne },
    { h: 'Request the release from Wien', p: 'Innsbruck departures need a release before take-off from the unit that takes them next: Wien Radar for the east, München for the north, Padova over the Brenner. Press <b>Request release</b> or type <code>AUA904 REL</code>. The call back comes on the landline (pink in the log).', cmd: 'AUA904 REL', ok: () => !!(A('AUA904') && A('AUA904').rel) || sn('AUA904').airborne },
    { h: 'Line up and backtrack', p: 'Alpha joins the runway about 400 m from the 08 end, so the E195 backtracks to the turn pad and turns round for the full length. Type <code>AUA904 LU</code>.', cmd: 'AUA904 LU', ok: () => st('AUA904','LINEUP','LINEDUP','TAKEOFF') || sn('AUA904').airborne },
    { h: 'Clear for take-off', p: 'With Wien’s release in, type <code>AUA904 CTO</code>. Watch the climb: the OBEDI 3J flies east along the valley on the OEJ localiser, past RUM and Rattenberg, with mountains close on both sides.', cmd: 'AUA904 CTO', ok: () => sn('AUA904').takeoff || sn('AUA904').airborne, wait: () => { const a = A('AUA904'); return !!a && !(a.rel && a.rel.st === 'OK' && !(a.rel.nb && S.t < a.rel.nb)); } },
    { h: 'Transfer to Innsbruck Radar', p: 'Once airborne, send it to Radar on 128.975 with <code>AUA904 HO</code>.', cmd: 'AUA904 HO', ok: () => (A('AUA904') && A('AUA904').freq === 'RAD') || sn('AUA904').exit },
    { h: 'Climb it and hand off to Wien', p: 'It follows the SID by itself. When it asks for more, climb it with <code>AUA904 A150</code> for FL150. When it is ready for transfer, send it to Wien Radar: <code>AUA904 HO 134.675</code> (or just <code>HO</code>).', cmd: ['AUA904 A150', 'AUA904 HO 134.675'], ok: () => (A('AUA904') && A('AUA904').handed) || sn('AUA904').exit, wait: () => { const a = A('AUA904'); return !!a && a.need !== 'Ready for transfer'; } }
  ],
  iarr: [
    { h: 'Take the initial call', p: 'KLM1993 from Amsterdam calls on the TULSI 3A towards Rattenberg (RTT), the start of every approach from the east. Select it and give a descent: <code>KLM1993 A95</code> for 9,500 feet, the minimum at RTT.', cmd: 'KLM1993 A95', ok: () => sn('KLM1993').cmd || sn('KLM1993').landed },
    { h: 'Clear the LOC/DME East', p: 'Type <code>KLM1993 APP</code>. From RTT it intercepts the OEV localiser at ADWIG, 21 miles out, and comes down the valley at 3.77°, steeper than a normal ILS, with check altitudes at each DME fix. The localiser is offset 3.5° from the runway.', cmd: 'KLM1993 APP', ok: () => !!(A('KLM1993') && A('KLM1993').app) || sn('KLM1993').landed },
    { h: 'Transfer to Tower', p: 'Once it is on the localiser, send it to Innsbruck Tower on 120.100 with <code>KLM1993 HO</code>.', cmd: 'KLM1993 HO', ok: () => (A('KLM1993') && A('KLM1993').freq === 'TWR') || sn('KLM1993').landed },
    { h: 'Clear to land', p: 'Type <code>KLM1993 CTL</code>. The missed approach point is at D4.5 OEV at 3,700 ft: from there the crew lands visually on 26.', cmd: 'KLM1993 CTL', ok: () => !!(A('KLM1993') && A('KLM1993').ctl) || sn('KLM1993').landed },
    { h: 'Watch the landing', p: 'Zoom in on the runway. After touchdown the aircraft rolls out west and asks to vacate.', ok: () => sn('KLM1993').landed && st('KLM1993','ROLLED','VACATING','ONSTAND') },
    { h: 'Vacate and taxi to stand', p: 'Type <code>KLM1993 VAC</code>. It taxies on along the runway, turns off at Alpha and follows taxiway Alpha east to the main apron.', cmd: 'KLM1993 VAC', ok: () => st('KLM1993','VACATING','ONSTAND') || sn('KLM1993').onstand }
  ],
  ifoehn: [
    { h: 'Föhn', p: 'A southerly gale is pouring over the Brenner: look at the ATIS panel. Föhn brings severe turbulence and downdraughts in the valley, and some crews will go around. EZY8341 from Gatwick is first in.', ok: () => !!(A('EZY8341') && A('EZY8341').need) || !!sn('EZY8341').cmd },
    { h: 'Descend and clear the approach', p: 'Give EZY8341 the approach in one go: <code>EZY8341 A95 APP</code>. It routes to RTT and down the LOC/DME East to runway 26.', cmd: 'EZY8341 A95 APP', ok: () => !!(A('EZY8341') && A('EZY8341').app) || sn('EZY8341').landed },
    { h: 'Start the departure', p: 'EWG7943 for Hamburg asks for start-up. Push it with <code>EWG7943 PUSH</code> and taxi it to Alpha with <code>EWG7943 TAXI A</code>. Its SID climbs east down the valley, straight at the arrivals coming the other way.', cmd: ['EWG7943 PUSH', 'EWG7943 TAXI A'], ok: () => st('EWG7943','TAXI','HOLDPT','LINEUP','LINEDUP','TAKEOFF') || sn('EWG7943').airborne, wait: () => { const a = A('EWG7943'); return !a || !(a.need || a.pushed); } },
    { h: 'Land the first arrival', p: 'Send EZY8341 to the Tower and clear it to land: <code>EZY8341 HO CTL</code>. If the föhn throws it around, it goes around and flies the missed approach back to RTT: clear it again with <code>APP</code>.', cmd: 'EZY8341 HO CTL', ok: () => !!(A('EZY8341') && A('EZY8341').ctl) || sn('EZY8341').landed },
    { h: 'Release and depart after the arrival', p: 'Opposite-direction traffic in a valley: the departure waits until the arrival has landed. Ask München for the release now with <code>EWG7943 REL</code>, then once EZY8341 is down and off the runway, <code>EWG7943 LU</code> and <code>EWG7943 CTO</code>.', cmd: ['EWG7943 REL'], ok: () => sn('EWG7943').takeoff || sn('EWG7943').airborne || !!(A('EWG7943') && A('EWG7943').rel) },
    { h: 'Land it and vacate', p: 'If the föhn throws EZY8341 into a go-around, it flies the missed approach back to RTT: clear it again with <code>EZY8341 A95 APP</code>, then <code>EZY8341 HO CTL</code>. Once it has rolled out, clear it off the runway: <code>EZY8341 VAC</code>.',
      get cmd(){ const a = A('EZY8341'); return !a || a.ground ? 'EZY8341 VAC' : !a.app ? 'EZY8341 A95 APP' : a.freq !== 'TWR' || !a.ctl ? 'EZY8341 HO CTL' : 'EZY8341 VAC'; },
      ok: () => st('EZY8341','VACATING','ONSTAND') || sn('EZY8341').onstand || sn('EWG7943').takeoff,
      wait: () => { const a = A('EZY8341'); return !a || (a.ground ? a.state !== 'ROLLED' : a.app && a.ctl); } },
    { h: 'Line up and go', p: 'Runway clear and released: <code>EWG7943 LU</code>, then <code>EWG7943 CTO</code>. A release is valid for ten minutes: if it ran out while the arrival went around, ask again with <code>EWG7943 REL</code>.',
      get cmd(){ const a = A('EWG7943'); return a && !(a.rel && ['OK','REQ'].includes(a.rel.st)) ? 'EWG7943 REL' : ['EWG7943 LU', 'EWG7943 CTO']; },
      ok: () => sn('EWG7943').takeoff || sn('EWG7943').airborne,
      wait: () => { const a = A('EWG7943'); if (!a || a.state !== 'HOLDPT') return true; if (!(a.rel && ['OK','REQ'].includes(a.rel.st))) return false; return !(a.rel.st === 'OK' && !(a.rel.nb && S.t < a.rel.nb)) || S.acs.some(o => o !== a && (o.onRwy || (o.app && !o.ground && o.state === 'FINAL'))); } },
    { h: 'Keep it below the next arrival', p: 'AUA903 from Vienna is holding at RTT at 11,000 ft, right on the departure track. Send EWG7943 to Radar and stop its climb at 8,000 ft, 3,000 ft under the hold: <code>EWG7943 HO A80</code>. Leave AUA903 in the hold for now.', cmd: 'EWG7943 HO A80', ok: () => (A('EWG7943') && A('EWG7943').freq === 'RAD') || sn('EWG7943').exit, wait: () => { const a = A('EWG7943'); return !a || a.ground; } },
    { h: 'Climb it once they have passed', p: 'When EWG7943 is east of RTT and moving away from the hold, the two have passed. Climb it with <code>EWG7943 A150</code>, then descend AUA903 and clear its approach: <code>AUA903 A95 APP</code>.',
      get cmd(){ const a = A('EWG7943'), b = A('AUA903'), c = []; if (a && !a.handed && (a.cleared ?? 0) < 15000) c.push('EWG7943 A150'); if (b && !b.ground && !b.app) c.push('AUA903 A95 APP'); return c.length ? c : null; },
      ok: () => (!!(A('AUA903') && A('AUA903').app) || sn('AUA903').landed) && (sn('EWG7943').exit || !!(A('EWG7943') && (A('EWG7943').handed || (A('EWG7943').cleared ?? 0) >= 15000))),
      wait: () => { const a = A('EWG7943'), b = A('AUA903'); return !a || !b || b.state === 'PRE' || Math.hypot(a.x - RADAR_REF[0], a.y - RADAR_REF[1]) < Math.hypot(WP.RTT.p[0] - RADAR_REF[0], WP.RTT.p[1] - RADAR_REF[1]) + 4; } },
    { h: 'Hand off and land', p: 'Send EWG7943 to München Radar with <code>EWG7943 HO</code> when it is ready for transfer, and bring AUA903 in: <code>AUA903 HO CTL</code> once it is on the localiser. If AUA903 goes around, clear it again with <code>AUA903 A95 APP</code>.',
      get cmd(){ const a = A('EWG7943'), b = A('AUA903'), c = [];
        if (a && !a.ground && !a.handed && (a.need === 'Ready for transfer' || Math.hypot(a.x - RADAR_REF[0], a.y - RADAR_REF[1]) > APT.handoffNM)) c.push('EWG7943 HO');
        if (b && !b.ground && !b.app) c.push('AUA903 A95 APP'); else if (b && !b.ground && !b.ctl) c.push('AUA903 HO CTL');
        return c.length ? c : null; },
      ok: () => ((A('EWG7943') && A('EWG7943').handed) || sn('EWG7943').exit) && (!!(A('AUA903') && A('AUA903').ctl) || sn('AUA903').landed) }
  ]
});
